projects:
  Event Chat:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/RealTimeChatAPI
        docsFilePath: src/graphql
        region: us-east-1
        apiId: ijejpaho6re2rmkfhxvgq6jeou
        maxDepth: 2
