/** Declaration file generated by dts-gen */

export const PR_ATTRIB_NAME: string;

export const PR_ATTRIB_VALUE: string;

export const PR_COMMENT: string;

export const PR_DECLARATION: string;

export const PR_KEYWORD: string;

export const PR_LITERAL: string;

export const PR_NOCODE: string;

export const PR_PLAIN: string;

export const PR_PUNCTUATION: string;

export const PR_SOURCE: string;

export const PR_STRING: string;

export const PR_TAG: string;

export const PR_TYPE: string;

export function createSimpleLexer(shortcutStylePatterns: any, fallthroughStylePatterns: any): any;

export function prettyPrint(opt_whenDone?: any, opt_root?: HTMLElement): any;

export function prettyPrintOne(sourceCodeHtml: any, opt_langExtension: any, opt_numberLines: any): any;

export function registerLangHandler(handler: any, fileExtensions: any): void;

export function sourceDecorator(options: any): any;

export namespace createSimpleLexer {
    const prototype: {
    };

}

export namespace prettyPrint {
    const prototype: {
    };

}

export namespace prettyPrintOne {
    const prototype: {
    };

}

export namespace registerLangHandler {
    const prototype: {
    };

}

export namespace sourceDecorator {
    const prototype: {
    };

}

