[build]
  command = "CI=false && yarn build"
  functions = "built-lambda"
  publish = "build"
  
[dev]
  port = 8080

[context.production.environment]
  REACT_APP_RMC_GITHUB_LAMBDA_URL = "https://ams7d66xwd.execute-api.us-east-1.amazonaws.com/live/graphql"

[context.deploy-preview.environment]
  REACT_APP_RMC_GITHUB_LAMBDA_URL = "https://ams7d66xwd.execute-api.us-east-1.amazonaws.com/dev/graphql"

[context.branch-deploy.environment]
  REACT_APP_RMC_GITHUB_LAMBDA_URL = "https://ams7d66xwd.execute-api.us-east-1.amazonaws.com/dev/graphql"